### ISSUE TITLE
Official Docker container at Docker Hub

### ISSUE THREAD

**Issue by alexanderadam** [codenoid/file.io#2]
It would be great if there would be [a Docker container at Docker hub](https://hub.docker.com/search?q=codenoid&type=image) for easy testing and installing.

Besides from that: it looks great so far!

**Comment by codenoid** [comment]
thankyou #3

**Comment by alexanderadam** [comment]
Nice, should the image already be on Docker Hub?
I can't find it but if it is: maybe it would make sense to mention it in the README?

**Comment by codenoid** [comment]
oopsie

**Comment by codenoid** [comment]
thankyou for the issue, It's my first time create/use docker image, now i felt in love with Docker

https://github.com/codenoid/file.io/blob/master/README.md#docker

**Comment by alexanderadam** [comment]
It works great! Awesome! :pray: 

Thank you so much!

**Comment by codenoid** [comment]
for config : 
```
docker run --env DB_URI=redis://127.0.0.1:6379/0 -p 3003:8080 codenoid/file.io-clone
```
